/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { InvoiceService } from "../invoice.service";
import { Public } from "../../decorators/public.decorator";
import { InvoiceCreateInput } from "./InvoiceCreateInput";
import { InvoiceWhereInput } from "./InvoiceWhereInput";
import { InvoiceWhereUniqueInput } from "./InvoiceWhereUniqueInput";
import { InvoiceFindManyArgs } from "./InvoiceFindManyArgs";
import { InvoiceUpdateInput } from "./InvoiceUpdateInput";
import { Invoice } from "./Invoice";
import { OrganizationFindManyArgs } from "../../organization/base/OrganizationFindManyArgs";
import { Organization } from "../../organization/base/Organization";
import { OrganizationWhereUniqueInput } from "../../organization/base/OrganizationWhereUniqueInput";

export class InvoiceControllerBase {
  constructor(protected readonly service: InvoiceService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Invoice })
  async create(@common.Body() data: InvoiceCreateInput): Promise<Invoice> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        direction: true,
        dueDate: true,
        id: true,
        paidDate: true,
        price: true,
        taxPointDate: true,
        updatedAt: true,
        uuid: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Invoice] })
  @ApiNestedQuery(InvoiceFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Invoice[]> {
    const args = plainToClass(InvoiceFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        direction: true,
        dueDate: true,
        id: true,
        paidDate: true,
        price: true,
        taxPointDate: true,
        updatedAt: true,
        uuid: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Invoice })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: InvoiceWhereUniqueInput
  ): Promise<Invoice | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        direction: true,
        dueDate: true,
        id: true,
        paidDate: true,
        price: true,
        taxPointDate: true,
        updatedAt: true,
        uuid: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Invoice })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: InvoiceWhereUniqueInput,
    @common.Body() data: InvoiceUpdateInput
  ): Promise<Invoice | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          direction: true,
          dueDate: true,
          id: true,
          paidDate: true,
          price: true,
          taxPointDate: true,
          updatedAt: true,
          uuid: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Invoice })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: InvoiceWhereUniqueInput
  ): Promise<Invoice | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          direction: true,
          dueDate: true,
          id: true,
          paidDate: true,
          price: true,
          taxPointDate: true,
          updatedAt: true,
          uuid: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @Public()
  @common.Get("/:id/organization")
  @ApiNestedQuery(OrganizationFindManyArgs)
  async findManyOrganization(
    @common.Req() request: Request,
    @common.Param() params: InvoiceWhereUniqueInput
  ): Promise<Organization[]> {
    const query = plainToClass(OrganizationFindManyArgs, request.query);
    const results = await this.service.findOrganization(params.id, {
      ...query,
      select: {
        code: true,
        createdAt: true,
        id: true,

        invoices: {
          select: {
            id: true,
          },
        },

        name: true,
        updatedAt: true,
        uuid: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/organization")
  async connectOrganization(
    @common.Param() params: InvoiceWhereUniqueInput,
    @common.Body() body: OrganizationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      organization: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/organization")
  async updateOrganization(
    @common.Param() params: InvoiceWhereUniqueInput,
    @common.Body() body: OrganizationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      organization: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/organization")
  async disconnectOrganization(
    @common.Param() params: InvoiceWhereUniqueInput,
    @common.Body() body: OrganizationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      organization: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
